### ISSUE TITLE
Add default EE form less file

### ISSUE THREAD

**Issue by reinos** [Dunique/generator-dunique#6]
``` less
//first we include the default style from forms
/* STANDARD FIELDS */
.dform_container input.text {
  outline-style: none;
  font-family: inherit;
  padding: 2px 0 2px 0;
  letter-spacing: normal;
}

.dform_container textarea {
  outline-style: none;
  font-family: inherit;
  letter-spacing: normal;
  padding: 2px 0 2px 0;
  resize: none
}

.dform_container select {
  font-family: inherit;
  padding: 3px 0 3px 0;
  letter-spacing: normal
}

.dform_container label {
  display:block;
}

.dform_element {margin:5px 0 10px;}


/* FIELD LABEL */
.dform_element .dform_label {
  font-weight: bold;
}

.dftop_label .dform_label {
  margin: 10px 0 4px 0;
  display: -moz-inline-stack;
  display: inline-block;
  line-height: 1.3em;
  clear: both
}

.dfbottom_label .dform_label {
  margin:4px 0 10px 0;
  display: -moz-inline-stack;
  display: inline-block;
  line-height: 1.3em;
  clear: both
}

.dfleft_label .dform_label {
    float: left;
    margin: 2px 15px 0 0;
    width: 29%;
}

.dfright_label .dform_label {
  float: right;
  margin: 0 15px 0 0;
  width: 29%;
  text-align: right
}

/* FIELD ERROR */
.dform_element .dform_error {
  font-weight:bold;
  color:red;
}

/* INPUT CONTAINER */
.dfleft_label div.dform_container, .dfright_label div.dform_container {
    float: left;
    width: 64%;
}

.dform_container label {font-weight:normal}

/* INNER CONTRAINERS */
.dform_container .dfinput_left,
.dform_container .dfinput_right,
.dform_container .dfinput_full {
    display: block;
    min-height: 43px;
    overflow: hidden;
  margin-bottom:10px;
}

.dform_container .dfinput_left {
    float: left;
    width: 50%;
}

.dfinput_left input.text,
.dfinput_right input.text {
    width: 60%;
}

.dform_container .dfinput_right {
    float: right;
    width: 49%;
}


/* DATE FIELD */
.dfinput_dates .df_date_elem {width:70px; float:left;}
.dfinput_dates .df_date_elem_extra {width:100px; float:left;}
.dfinput_dates label {display:block;}
.dfinput_dates input.text {width:90%;}
.dfinput_dates select {width:90%;}

/* TIMES FIELD */
.dfinput_times .df_time_elem {width:70px; float:left;}
.dfinput_times label {display:block;}
.dfinput_times input.text {width:80%;}

/* PHONE FIELD */
.dfinput_phones .phone_cc {width:15%;}
.dfinput_phones .phone_area {width:15%;}
.dfinput_phones .phone_number {width:40%;}
.dfinput_phones .phone_extension {width:12.5%;}
.dfinput_phones input.text {width:90%;}

/* NAME FIELD */
.dfinput_names .name_prefix {width:15%;}
.dfinput_names .name_first {width:30%;}
.dfinput_names .name_last {width:30%;}
.dfinput_names .name_suffix {width:15%;}
.dfinput_names input.text {width:90%;}

/* ADDRESS FIELD */
.dform_address input.text {width:90%;}
.dform_address .address_state input.text {width:80%;}
.dform_address .address_country select {width:80%;}

/* PRODUCTS FIELD */
.dfinput_products .df_qty_elem {width:70px; float:left;}
.dfinput_products .df_products_elem {width:150px; float:left;}
.dfinput_products label {display:block;}
.dfinput_products input.text {width:90%;}
.dfinput_products select {width:90%;}

/* RADIO/CHECKBOX */
.dform_element .checkboxes,
.dform_element .radios {list-style:none; padding:0}

/* COLUMNS */
.dfcolumns {}
.dfcolumns .column {min-height:100px; float:left;}

/* FORM CONFIRMATION MESSAGE */
.dform_confirmation {background-color:#DFF0D8; border:1px solid #D6E9C6; color:#468847; border-radius:4px 4px 4px 4px; margin-bottom:18px; padding:8px 35px 8px 14px;}

/* CART */
.dform_container .cart_qty_small {text-align:center; width:30px;}

/* CREDIT CARD */
.cc_number {position:relative;}
.cc_number input {width:150px;}
.cc_name input {width:300px;}
.cc_logos {
  height:32px;
  margin-bottom:5px;
  position:absolute;
    left:160px;
    top:-4px;
}
.cc_logos .cc_icons {
  background-image: url(img/creditcard_icons.png);
  background-repeat: no-repeat;
    float: left;
    height: 36px;
    margin-right: 4px;
    text-indent: -9000px;
    width: 36px;
}
.cc_logos .cc-visa {background-position: 0 0;}
.cc_logos .cc-mc {background-position: -36px 0;}
.cc_logos .cc-amex {background-position: -72px 0;}
.cc_logos .cc-discover {background-position: -108px 0;}
.cc_logos .cc-jcb {background-position: -180px 0;}
.cc_cardinfo {width:400px}
.cc_cardinfo .info_block {width:40%; float:left;}
.cc_cardinfo .exp_month {width:40%; margin-right:9%;}
.cc_cardinfo .exp_year {width:40%;}
.cc_cardinfo .cc_ccv {position:relative;}
.cc_cardinfo .cc_ccv input {width:50px;}
.cc_cardinfo .ccv_img {background-image: url(img/creditcard_icons.png);
  background-position: 0 -128px;
  background-repeat: no-repeat;
  display: block;
  height: 23px;
  left: 60px;
  position: absolute;
  width: 32px;
  top:0
}



/* Cart Product Options Muli */
.dform_cart_product_options_multi tfoot th {text-align:left}
.dform_cart_product_options_multi .del {text-align:left}
.dform_cart_product_options_multi .qty {width:50px;}

//
// Forms
// --------------------------------------------------


// Normalize non-controls
//
// Restyle and baseline non-control form elements.

.dform {

  fieldset {
    padding: 0;
    margin: 0;
    border: 0;
    background: #fff;
  }

  legend {
    top: 20px;
    position: relative;
    display: block;
    width: 100%;
    padding: 0 0 0 10px;
    margin-bottom: @line-height-computed * 1.5;
    font-size: (@font-size-base * 1.5);
    line-height: inherit;
    color: @legend-color;
    border: 0;
    border-bottom: 1px solid @legend-border-color;
  }

  .checkboxes,
  .radios {
    list-style:none;
    margin:0;
    padding:0;

    li {
      margin-top:2px !important;
      margin-bottom:2px !important;
    }
  }





  // Common form controls
  //
  // Shared size and type resets for form controls. Apply `.form-control` to any
  // of the following form controls:
  //
  // select
  // textarea
  // input[type="text"]
  // input[type="password"]
  // input[type="datetime"]
  // input[type="datetime-local"]
  // input[type="date"]
  // input[type="month"]
  // input[type="time"]
  // input[type="week"]
  // input[type="number"]
  // input[type="email"]
  // input[type="url"]
  // input[type="search"]
  // input[type="tel"]
  // input[type="color"]

  .dform_container input.text,
  .dform_container textarea,
  .dform_container select,
   {
    display: block;
    width: 100%;
   // height: @input-height-base; // Make inputs at least the height of their button counterpart (base line-height + padding + border)
    padding: @padding-base-vertical @padding-base-horizontal;
    font-size: @font-size-base;
    line-height: @line-height-base;
    color: @input-color;
    vertical-align: middle;
    background-color: @input-bg;
    background-image: none; // Reset unusual Firefox-on-Android default style; see https://github.com/necolas/normalize.css/issues/214
    border: 1px solid @input-border;
    border-radius: @input-border-radius;
    .box-shadow(inset 0 1px 1px rgba(0,0,0,.075));
    .transition(~"border-color ease-in-out .15s, box-shadow ease-in-out .15s");

    // Customize the `:focus` state to imitate native WebKit styles.
    .form-control-focus();

    // Placeholder
    //
    // Placeholder text gets special styles because when browsers invalidate entire
    // lines if it doesn't understand a selector/
    .placeholder();

    // Disabled and read-only inputs
    // Note: HTML5 says that controls under a fieldset > legend:first-child won't
    // be disabled if the fieldset is disabled. Due to implementation difficulty,
    // we don't honor that edge case; we style them as disabled anyway.
    &[disabled],
    &[readonly],
    fieldset[disabled] & {
      cursor: not-allowed;
      background-color: @input-bg-disabled;
    }

    // Reset height for `textarea`s
    textarea& {
      height: auto;
    }
  }


  // Form groups
  //
  // Designed to help with the organization and spacing of vertical forms. For
  // horizontal forms, use the predefined grid classes.

  .dform_container {
    margin-bottom: 15px;
  }


  // Checkboxes and radios
  //
  // Indent the labels to position radios/checkboxes as hanging controls.

  .radios li,
  .checkboxes li {
    display: block;
    min-height: @line-height-computed; // clear the floating input if there is no label text
    margin-top: 10px;
    margin-bottom: 10px;
    padding-left: 20px;
    vertical-align: middle;
    label {
      display: inline;
      margin-bottom: 0;
      font-weight: normal;
      cursor: pointer;
    }
  }
  .radios input[type="radio"],
  .radio-inline input[type="radio"],
  .checkboxes input[type="checkbox"],
  .checkbox-inline input[type="checkbox"] {
    float: left;
    margin-left: -20px;
  }
  .radios li + .radios li,
  .checkboxes li + .checkboxes li {
    margin-top: -5px; // Move up sibling radios or checkboxes for tighter spacing
  }



  // Apply same disabled cursor tweak as for inputs
  //
  // Note: Neither radios nor checkboxes can be readonly.
  input[type="radio"],
  input[type="checkbox"],
  .radios li,
  .radio-inline,
  .checkboxes li,
  .checkbox-inline {
    &[disabled],
    fieldset[disabled] & {
      cursor: not-allowed;
    }
  }


  // Help text
  //
  // Apply to any element you wish to create light text for placement immediately
  // below a form control. Use for general help, formatting, or instructional text.

  .dform_desc {
    display: block; // account for any element using help-block
    margin-top: 5px;
    margin-bottom: 10px;
    color: lighten(@text-color, 25%); // lighten the text some for contrast
  }

  .submit {
    .btn;
    .btn-primary;
  }

  .dfcolumns {
    padding:0 10px;
  }

  .dfbottom_label {
    .dform_container {
      margin-bottom:5px;
    }
  }


  .dform_error {
    display: block;
    margin-bottom: -7px;
    color: #ff0000;
    //background: lighten(#ff0000,40%);
    padding: 3px 8px 8px 0;
    font-weight: bold;
    //font-size: @basefont * 0.9;
    //border: 1px solid #ff0000;
    border-bottom: 0;
  }

  .dform_error ~ .dform_container {
    /*background: lighten(#ff0000,40%);
    padding: 4px;
    border: 1px solid #ff0000;
    border-top: 0;*/

    input {
      border: 1px solid #ff0000;
    }
  }

}
```
